<?php

namespace Tests\Feature\Http\Controllers;

use App\Billing\FakePaymentGateway;
use App\Billing\PaymentGateway;
use App\Billing\StripePaymentGateway;
use App\Models\Donation;
use App\Mail\DonationEmail;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Mail;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\DonationsController
 */
class DonationsControllerTest extends TestCase
{
    use RefreshDatabase;

    public $paymentGateway;

    protected function setUp(): void
    {
        parent::setUp();

        $this->paymentGateway = new FakePaymentGateway(getStripeSecret('institute'));
        $this->app->instance(PaymentGateway::class, $this->paymentGateway);
    }

    /** @test */
    public function create_returns_an_ok_response()
    {
        $response = $this->get('donations/create');

        $response->assertOk();
    }

    /** @test */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $donation = Donation::factory()->create();

        $response = $this->get('donations/{hash}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /** @test */
    public function user_can_make_subscription_donation_to_the_institute()
    {
        Mail::fake();
        $stripePaymentGateway = new StripePaymentGateway(getStripeSecret('institute'));
        $this->app->instance(PaymentGateway::class, $stripePaymentGateway);

        $user = User::factory()->create([
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
        ]);

        $response = $this->withoutExceptionHandling()
            ->actingAs($user)->json('post', '/donations', [
                'amount' => 25,
                'name' => 'Harry Potter',
                'email' => 'hpotter@hogwarts.edu',
                'subscription' => 'monthly',
                'group' => 'institute',
                'payment_token' => $stripePaymentGateway->getValidTestToken(),
            ]);

        $response->assertStatus(201);

        $donation = Donation::where('email', 'hpotter@hogwarts.edu')->first();

        $this->assertNotNull($donation);
        $this->assertNotNull($donation->hash);
        $this->assertEquals(2500, $donation->amount);
        $this->assertEquals('Harry Potter', $donation->name);
        $this->assertEquals('hpotter@hogwarts.edu', $donation->email);
        $this->assertEquals('monthly-25', $donation->subscription->plan);
        $this->assertNotNull($donation->subscription->next_charge);
        $this->assertTrue($donation->subscription->active);
        $this->assertNotNull($donation->subscription->subscription_id);
        $this->assertNotNull($donation->receipt->transaction_id);
        $this->assertEquals($user->id, $donation->user_id);

        Mail::assertSent(DonationEmail::class, function ($mail) use ($donation) {
            return $mail->hasTo('hpotter@hogwarts.edu')
                && $mail->donation->id === $donation->id;
        });
    }

    /** @test */
    public function user_can_make_subscription_donation_to_mblgtacc()
    {
        Mail::fake();
        $stripePaymentGateway = new StripePaymentGateway(getStripeSecret('institute'));
        $this->app->instance(PaymentGateway::class, $stripePaymentGateway);
        $stripePaymentGateway->setApiKey(getStripeSecret('mblgtacc'));

        $user = User::factory()->create([
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
        ]);

        $response = $this->withoutExceptionHandling()
            ->actingAs($user)->json('post', '/donations', [
                'amount' => 25,
                'name' => 'Harry Potter',
                'email' => 'hpotter@hogwarts.edu',
                'subscription' => 'monthly',
                'group' => 'mblgtacc',
                'payment_token' => $stripePaymentGateway->getValidTestToken(),
            ]);

        $response->assertStatus(201);

        $donation = Donation::where('email', 'hpotter@hogwarts.edu')->first();

        $this->assertNotNull($donation);
        $this->assertNotNull($donation->hash);
        $this->assertEquals(2500, $donation->amount);
        $this->assertEquals('Harry Potter', $donation->name);
        $this->assertEquals('hpotter@hogwarts.edu', $donation->email);
        $this->assertEquals('monthly-25', $donation->subscription->plan);
        $this->assertNotNull($donation->subscription->next_charge);
        $this->assertTrue($donation->subscription->active);
        $this->assertNotNull($donation->subscription->subscription_id);
        $this->assertNotNull($donation->receipt->transaction_id);
        $this->assertEquals($user->id, $donation->user_id);

        Mail::assertSent(DonationEmail::class, function ($mail) use ($donation) {
            return $mail->hasTo('hpotter@hogwarts.edu')
                && $mail->donation->id === $donation->id;
        });
    }

    /** @test */
    public function visitor_can_make_one_time_donation_to_the_institute()
    {
        Mail::fake();

        $response = $this->withoutExceptionHandling()->json('post', '/donations', [
            'amount' => 15,
            'group' => 'institute',
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
            'subscription' => 'no',
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(201)
            ->assertJsonStructure([
                'donation', 'redirect',
            ]);

        $donation = Donation::where('email', 'hpotter@hogwarts.edu')->first();

        $this->assertNotNull($donation);
        $this->assertEquals(1500, $this->paymentGateway->totalCharges());
        $this->assertEquals(1500, $donation->amount);
        $this->assertEquals('Harry Potter', $donation->name);
        $this->assertEquals('hpotter@hogwarts.edu', $donation->email);
        $this->assertNotNull($donation->hash);
        $this->assertNull($donation->user_id);
        $this->assertNotNull($donation->receipt->transaction_id);

        Mail::assertSent(DonationEmail::class, function ($mail) use ($donation) {
            return $mail->hasTo('hpotter@hogwarts.edu')
                && $mail->donation->id === $donation->id;
        });
    }

    /** @test */
    public function visitor_can_make_one_time_donation_to_the_mblgtacc()
    {
        Mail::fake();

        $response = $this->withoutExceptionHandling()->json('post', '/donations', [
            'amount' => 15,
            'group' => 'mblgtacc',
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
            'subscription' => 'no',
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(201)
            ->assertJsonStructure([
                'donation', 'redirect',
            ]);

        $donation = Donation::where('email', 'hpotter@hogwarts.edu')->first();

        $this->assertNotNull($donation);
        $this->assertEquals(1500, $this->paymentGateway->totalCharges());
        $this->assertEquals(1500, $donation->amount);
        $this->assertEquals('Harry Potter', $donation->name);
        $this->assertEquals('hpotter@hogwarts.edu', $donation->email);
        $this->assertNotNull($donation->hash);
        $this->assertNull($donation->user_id);
        $this->assertNotNull($donation->receipt->transaction_id);

        Mail::assertSent(DonationEmail::class, function ($mail) use ($donation) {
            return $mail->hasTo('hpotter@hogwarts.edu')
                && $mail->donation->id === $donation->id;
        });
    }

    /** @test */
    public function user_can_make_one_time_donation_to_the_institute()
    {
        Mail::fake();

        $user = User::factory()->create([
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
        ]);

        $response = $this->withoutExceptionHandling()
            ->actingAs($user)->json('post', '/donations', [
                'amount' => 25,
                'group' => 'institute',
                'name' => 'Harry Potter',
                'email' => 'hpotter@hogwarts.edu',
                'subscription' => 'no',
                'payment_token' => $this->paymentGateway->getValidTestToken(),
            ]);

        $response->assertStatus(201);

        $donation = Donation::where('email', 'hpotter@hogwarts.edu')->first();

        $this->assertNotNull($donation);
        $this->assertEquals(2500, $this->paymentGateway->totalCharges());
        $this->assertEquals(2500, $donation->amount);
        $this->assertEquals('Harry Potter', $donation->name);
        $this->assertEquals('hpotter@hogwarts.edu', $donation->email);
        $this->assertNotNull($donation->receipt->transaction_id);
        $this->assertEquals($user->id, $donation->user_id);

        Mail::assertSent(DonationEmail::class, function ($mail) use ($donation) {
            return $mail->hasTo('hpotter@hogwarts.edu')
                && $mail->donation->id === $donation->id;
        });
    }

    /** @test */
    public function user_can_make_one_time_donation_to_mblgtacc()
    {
        Mail::fake();

        $user = User::factory()->create([
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
        ]);

        $response = $this->withoutExceptionHandling()
            ->actingAs($user)->json('post', '/donations', [
                'amount' => 25,
                'group' => 'mblgtacc',
                'name' => 'Harry Potter',
                'email' => 'hpotter@hogwarts.edu',
                'subscription' => 'no',
                'payment_token' => $this->paymentGateway->getValidTestToken(),
            ]);

        $response->assertStatus(201);

        $donation = Donation::where('email', 'hpotter@hogwarts.edu')->first();

        $this->assertNotNull($donation);
        $this->assertEquals(2500, $this->paymentGateway->totalCharges());
        $this->assertEquals(2500, $donation->amount);
        $this->assertEquals('Harry Potter', $donation->name);
        $this->assertEquals('hpotter@hogwarts.edu', $donation->email);
        $this->assertNotNull($donation->receipt->transaction_id);
        $this->assertEquals($user->id, $donation->user_id);

        Mail::assertSent(DonationEmail::class, function ($mail) use ($donation) {
            return $mail->hasTo('hpotter@hogwarts.edu')
                && $mail->donation->id === $donation->id;
        });
    }

    /** @test */
    public function can_make_one_time_donation_with_company_information()
    {
        Mail::fake();

        $response = $this->withoutExceptionHandling()->json('post', '/donations', [
            'amount' => 15,
            'group' => 'institute',
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
            'subscription' => 'no',
            'company' => 'Hogwarts School of Witchcraft and Wizardry',
            'tax_id' => 123123123,
            'payment_token' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(201);

        $donation = Donation::where('email', 'hpotter@hogwarts.edu')->first();

        $this->assertNotNull($donation);
        $this->assertEquals('Hogwarts School of Witchcraft and Wizardry', $donation->company);
        $this->assertEquals(123123123, $donation->tax_id);

        Mail::assertSent(DonationEmail::class, function ($mail) use ($donation) {
            return $mail->hasTo('hpotter@hogwarts.edu')
                && $mail->donation->id === $donation->id;
        });
    }

    /** @test */
    public function donation_is_not_created_if_charge_fails()
    {
        $response = $this->withoutExceptionHandling()->json('post', '/donations', [
            'amount' => 15,
            'group' => 'institute',
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
            'subscription' => 'no',
            'stripeToken' => 'invalid-payment-token',
        ]);

        $response
            ->assertStatus(422)
            ->assertJsonStructure([
                'created',
                'message',
            ]);

        $this->assertNull(Donation::where('email', 'hpotter@hogwarts.edu')->first());
    }

    /** @test */
    public function amount_is_required()
    {
        $response = $this->json('post', '/donations', [
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
            'group' => 'institute',
            'subscription' => 'no',
            'stripeToken' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(422)
            ->assertJsonHasErrors('amount');
    }

    /** @test */
    public function amount_must_be_at_least_five()
    {
        $response = $this->json('post', '/donations', [
            'amount' => 4,
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
            'group' => 'institute',
            'subscription' => 'no',
            'stripeToken' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(422)
            ->assertJsonHasErrors('amount');
    }

    /** @test */
    public function amount_must_less_than_a_million()
    {
        $response = $this->json('post', '/donations', [
            'amount' => 1000000,
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
            'group' => 'institute',
            'subscription' => 'no',
            'stripeToken' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(422)
            ->assertJsonHasErrors('amount');
    }

    /** @test */
    public function name_is_required()
    {
        $response = $this->json('post', '/donations', [
            'amount' => 10,
            'group' => 'institute',
            'email' => 'hpotter@hogwarts.edu',
            'subscription' => 'no',
            'stripeToken' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(422)
            ->assertJsonHasErrors('name');
    }

    /** @test */
    public function email_is_required()
    {
        $response = $this->json('post', '/donations', [
            'amount' => 10,
            'group' => 'institute',
            'name' => 'Harry Potter',
            'subscription' => 'no',
            'stripeToken' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(422)
            ->assertJsonHasErrors('email');
    }

    /** @test */
    public function company_and_tax_id_are_required_if_is_company_is_true()
    {
        $response = $this->json('post', '/donations', [
            'amount' => 10,
            'group' => 'institute',
            'name' => 'Harry Potter',
            'email' => 'hpotter@hogwarts.edu',
            'subscription' => 'no',
            'is_company' => true,
            'stripeToken' => $this->paymentGateway->getValidTestToken(),
        ]);

        $response->assertStatus(422)
            ->assertJsonHasErrors(['company', 'tax_id']);
    }
}
