<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\OrdersController
 */
class OrdersControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $order = factory(\App\Order::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->delete('orders/{order}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $order = factory(\App\Order::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get('orders/{id}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
