<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\InvoicesController
 */
class InvoicesControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $invoice = factory(\App\Invoice::class)->create();

        $response = $this->get('admin/invoices/{invoice}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
