name: Duster Lint

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
  duster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Duster Lint"
        run: vendor/bin/duster lint
        with:
          args: lint
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: 8
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: "pnpm"
        - name: Install dependencies
          run: pnpm install -D
        - name: Check formatting with Prettier
          run: pnpm prettier:check:ci
